#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2.console.enabled: true
#server:
#  port: 3000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/testdb
    username: admin
    password: admin
    
server:
  port: 3000