version: '3'
services:
  db:
    hostname: g-test-db
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
        - .:/tmp/
    tty: true
    stdin_open: true